### ISSUE TITLE
Toggle Edit Bug

### ISSUE THREAD

**Issue by ob7** [InstantUpdate/CMS#11]
Ok some of my comments have been over misconfiguration on my part, but here is a real issue I may have found.

When toggle edits, things are fine, edits are made.  But when I go to stop editing, and toggle the editor off, nothing happens, and the debug console shows an error everytime I click it:

Uncaught The editor instance "my-editable-id" is already attached to the provided element.

So what now?  How to fix this problem I wonder?

**Comment by ob7** [comment]
ckeditor.js:319 Uncaught TypeError: Cannot read property 'getEditor' of undefinedCKEDITOR.inline @ ckeditor.js:319enable_snapeditor @ ?g=base-js:11(anonymous function) @ ?g=base-js:25v.extend.each @ jquery.js:2v.fn.v.each @ jquery.js:2toggle_snapeditor @ ?g=base-js:21menu_items.push.onClick @ ?g=user-js:32_bindMenu.t @ ?g=user-js:22(anonymous function) @ ?g=user-js:23v.event.dispatch @ jquery.js:2v.event.add.o.handle.u @ jquery.js:2

ckeditor.js:319 Uncaught The editor instance "my-editable-id" is already attached to the provided element.

I've tried removing all JS from the page and still not fix.  If I remove all editable id's the second error goes away, but the first remains:

Uncaught TypeError: Cannot read property 'getEditor' of undefined

**Comment by ob7** [comment]
Errors seem to occur if an item is selected to edit, and toggle off editing is clicked without clicking save inside editor for item...

**Comment by avramovic** [comment]
I'm not able to reproduce this with our online demo, which most likely means it's a conflict between your HTML template and IU's JavaScript code.

Can you try it with another HTML template, just so we can figure out if it's a conflict with your template and our JS code or something else?

**Comment by ob7** [comment]
Its only happening with certain pages of a custom build html site.  I'm not sure whats causing it though, its only on some pages, and only some of the time.  Except for the contact page, that pages throughs errors no matter what, must be in conflict with the form code.  On another note, where could I start in helping extend the code to have repeatable elements?
