### ISSUE TITLE
Locking usera to certain pages

### ISSUE THREAD

**Issue by ob7** [InstantUpdate/CMS#13]
Is there a way to make a user that can only edit certain pages???

**Comment by Webinsane** [comment]
You can assign the user to the specific page or content. To allow users editing only certain page contents, edit particular content and set it's editors instead!

**Comment by ob7** [comment]
Can you explain what you mean?  I don't understand.

**Comment by avramovic** [comment]
You can add non-admin users as editors of only those pages you want them to edit, or you can add them as editors of only some contents (blocks) within same page. You can add them while editing page/content in the back-end area.
