### ISSUE TITLE
jquery is not hard linked in admin

### ISSUE THREAD

**Issue by ob7** [InstantUpdate/CMS#14]
Hey crew, theres a broken link here: auth_login.php

<script type="text/javascript" src="<?php echo $template->base_url(); ?>http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js"></script>

should be:

<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js"></script>

**Comment by avramovic** [comment]
Can you be more specific? What is exactly broken?

**Comment by ob7** [comment]
I'm sorry the markdown removed the code I pasted:
line 15 of auth_login.php
'''
<script type="text/javascript" src="<?php echo $template->base_url(); ?>http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js"></script>
'''

**Comment by avramovic** [comment]
You can remove that line altogether as jQuery is already loaded on line #10. I will fix it in the source.
