### ISSUE TITLE
SVG's no worky worky!

### ISSUE THREAD

**Issue by ob7** [InstantUpdate/CMS#15]
As soon as I plug my template into IU, no SVG's will load.  I have to convert all SVG's to PNG's and load those if I want to use Instant Update....  Wuts up with that yo?  How do we fix fixy!

**Comment by ob7** [comment]
Sorry for my sarcasm, but seriously, SVG's won't work???

**Comment by dplesh** [comment]
Did you get it fixed? If so, do you mind to elaborate?

**Comment by ob7** [comment]
Yea I switched to Concrete5

**Comment by Webinsane** [comment]
This was actually simple problem. All you have to do is to add:

'svg'   =>  array('image/svg+xml'),

https://github.com/InstantUpdate/CMS/commit/90b3c6a5c46c11f35a1dee8d93a8afdd81cc5bf1

Let me know if this fixed it.

**Comment by dplesh** [comment]
Yeap, that fixed it, thanks!
