### ISSUE TITLE
Absolute link fix when rewriting enabled

### ISSUE THREAD

**Issue by ob7** [InstantUpdate/CMS#16]
So if you have rewriting enabled, and your site has any absolute links like this:
a href="/services/location.html"
and your at /services/location.html and you click the link, the link becomes
/services//services/location.html
How to fix this?

**Comment by avramovic** [comment]
That should not happen if your link is like this: a href="/services/location.html"

It is possible if it's like this: a href="services/location.html", but that's normal behavior for relative links.

**Comment by ob7** [comment]
I'm not sure why I was having this problem before, as I tried to replicate it to no avail.

**Comment by ob7** [comment]
I was able to reproduce this again:

Example:
http://chaz.ob7.us/services/index.php
Open up dev console, see the missing style sheet?  See how its trying to load it from services directory instead of root? And see the extra '/'?  In the php file, this is the code to import that stylesheet:
```
<link rel="stylesheet" href="/css/landing.css">
```

**Comment by ob7** [comment]
To help clarify on this, it only happens when linking css or js files, normal href links work as they should.  See my example above.

**Comment by ob7** [comment]
Another way to reproduce this, go to the site: chaz.ob7.us, click on services.  The link in code is /services/index.php, but look at the code and see that its making the link have two // instead of one.  Its treating the root link as if it had a . infront of it.

**Comment by ob7** [comment]
Another clear example: Go to chaz.ob7.us, click on services, then use the menu on the bottom and click on contact, instead of taking you to /contact.php, it takes you to http://chaz.ob7.us/services//contact.php, see the double slash??? It shouldn't be stuck in services directory. Its treating the backslash like an ordinary character!

**Comment by ob7** [comment]
Ive disabled .htaccess for now because of the links, and also its stopping contact form captcha from being generated.  I will look into this more, for now, I've had to disable.

Thanks,
David

**Comment by ob7** [comment]
FWIW you can still see the extra slash being added to links that are absolute, even with htaccess turned off, example: http://chaz.ob7.us/index.php//testimonials.php

**Comment by ob7** [comment]
Ok figured out the sub directory links atleast... the .htaccess file needs to be copied to subdirectory.

**Comment by ob7** [comment]
Solution was to hard link everything to the domain using php, as the .htaccess file rewrites the links with a / even if one is already present in the beginning of the link.
