### ISSUE TITLE
version

### ISSUE THREAD

**Issue by GaneshKandu** [InstantUpdate/CMS#19]
I have installed Instant Update 0.2.2 <a href="https://github.com/InstantUpdate/CMS/archive/v0.2.2.zip">Instant Update 0.2.2</a> but installed.txt shows 0.2.1

and getting Fettle Error
![untitled-1](https://cloud.githubusercontent.com/assets/12833130/11056835/af928faa-87ab-11e5-88aa-3ace0ec46ac5.png)

on index.php/administration/users/edit/1 page

**Comment by avramovic** [comment]
Can you re-download and try again? It should fix the version number, but I can't reproduce that fatal error. Let's see if reinstalling will make it disappear.

**Comment by GaneshKandu** [comment]
Thanks
