### ISSUE TITLE
Some strange errors within input.php and process.php

### ISSUE THREAD

**Issue by WebCrew** [InstantUpdate/CMS#20]
**First error:**

A PHP Error was encountered

Severity: Warning

Message: Cannot modify header information - headers already sent by (output started at /var/www/web917/html/webcrew/iu-system/core/Exceptions.php:170)

Filename: core/Input.php

Line Number: 250
--------------------------------------------------------------
**Next Error:**

HP Error was encountered

Severity: 8192

Message: Non-static method BrowserOS::get_browser_no_version() should not be called statically, assuming $this from incompatible context

Filename: controllers/process.php

Line Number: 167
--------------------------------------------------------------

**Last Error:**

Severity: 8192
Message: Non-static method BrowserOS::get_os() should not be called statically, assuming $this from incompatible context

Filename: controllers/process.php

Line Number: 166
---------------------------------------------------------------

I hope You can fix it and find a solution for it. I`m using a shared hosting with php 5.6

Kind regards, Andy

**Comment by avramovic** [comment]
The last two issues should be fixed in v0.2.2 which is located here: https://github.com/InstantUpdate/CMS/releases/tag/v0.2.2

The first issue should disappear once last to are gone.

**Comment by WebCrew** [comment]
Thank You verry verry much - this was a awesome fast answer mate :) I like Your CMS so much, its so so cool :) thanks for the good work.
