### ISSUE TITLE
Question: Is this project maintained? What is the long term plan

### ISSUE THREAD

**Issue by fr00x** [InstantUpdate/CMS#28]
Hi,

I've just came across this project and I was wondering whether a) it's still under active maintenance and b) what the long term plan might look like.

Do you have plans to update Codeigniter or move away from it?

Thank you!

**Comment by WebCrew** [comment]
Hi mate :)

this nis not my project. You can find the Instant Update CMS in a more updated version here:
https://github.com/InstantUpdate/CMS

Kind regards, Andy

**Comment by fr00x** [comment]
Thank you - I know how hard that can be. I was asking as a possible user - so do not feel pressured to update migrate away. At this point of time, I will have to stay away as a user.

**Comment by yliefting** [comment]
With PHP5.6 now EOL and without security updates using Instant Update is now becoming difficult. Is there any plan to make IU ready for PHP7? How much work is needed to make the necessary changes? If it's not too much work I may be able to provide some resources.
