### ISSUE TITLE
Jekyll

### ISSUE THREAD

**Issue by veb** [InstantUpdate/CMS#3]
I've managed to get this to work with statically generated files from Jekyll, and it's awesome especially the inline editing stuff to boot.

You interested? I could do a pull request.

One thing that I have been bothered and trying to fix is all the index.php that keep appearing. Might have something to do with Jekyll being in a sub directory. I'll figure it out :-) Thanks for making this man!

**Comment by avramovic** [comment]
I haven't used Jekyll but if it's creating static HTML files then you should be able to integrate IU into those pages without any modifications. What exact problems you had and what you had to modify in the IU source to make it work?

All requests within IU are routed through index.php. If you are using Apache web server or any other web server which supports URL rewriting, you can hide index.php from your URLs (though we provide official support for Apache only): http://my.instant-update.com/t/url-handling-and-seo-links/30

**Comment by veb** [comment]
Yep. Did all the SEO stuff (I've had extensive work with CI) and well, bad things kept happening. 

I want to keep my Jekyll workflow as-is so I'll go back through that. Right now if I move the static files into the views, I can add via the dashboard and it looks good. However, I'm thinking it would be kinda cool if you didn't need to make the pages via the dashboard if they're already there sorta thing.

disclaimer: I've only had a few hours working with this CMS but already love it

**Comment by veb** [comment]
As per other comment, will g through everything again from scratch and keep a note of what goes wrong and modify stuff accordingly.

**Comment by avramovic** [comment]
> Yep. Did all the SEO stuff (I've had extensive work with CI) and well, bad things kept happening.

But what SEO stuff? You need to be more specific. IU already has SEO URLs (everything is routed through index.php, though you can hide it using .htaccess rules)

> However, I'm thinking it would be kinda cool if you didn't need to make the pages via the dashboard if they're already there sorta thing.

The "problem" is IU doesn't use your .html files as pages but as html templates. By using separate pages (in the database) you can have multiple pages share same html template (file). So you can have unlimited number of pages sharing same html template, having the same design (and making redesign way easier)

> disclaimer: I've only had a few hours working with this CMS but already love it

Thanks! :)

**Comment by Webinsane** [comment]
I am sorry for disturbance, but we will be closing issues on GitHub (probably next week). Please use our community if you have any suggestions, features, bugs etc. We also have GitHub registration enabled for easy signup. Our community software (Discourse) tracks any git code directly through the posts.

http://my.instant-update.com/

Thank you for your kind cooperation.

**Comment by veb** [comment]
Closing issues on GitHub to use the community instead? If the code is here, the issues/bugs and fixes should be here too. Otherwise, no point in using GitHub.

You can count me out.

**Comment by Webinsane** [comment]
We want to build a community and having two sources of support is not perfect solution for us. Our community is built with tools that show any GitHub code like this post:

http://my.instant-update.com/t/index-pretty-url/101/6

We have GitHub registration. It small thing to do if you do like and use our software.
