### ISSUE TITLE
MySQL DB loader

### ISSUE THREAD

**Issue by veb** [InstantUpdate/CMS#4]
I've noticed that some things like the mysql_escape_string has been deprecated from 5.3 and therefore causes errors.

I've made a patch if you want to peer review it. I think that part of making sure data injection is good could be improved on which I may do later today. I'll submit now.

**Comment by veb** [comment]
mysqli and stuff will probably have the same issue.

**Comment by avramovic** [comment]
If they are deprecated then they are working but throwing notice that it is deprecated and will eb removed. You should remove notices from error reporting and it will still work.

If they are removed, then you can't use MySQL driver, you'll have to use MySQLi which isn't deprecated and shouldn't have the same issues. I.e. This is NOT marked as deprecated: http://php.net/manual/en/mysqli.real-escape-string.php

**Comment by veb** [comment]
Odd, because when I changed to mysqli, the same warnings kept appearing! 

I'll investigate more when I do a from-scratch.
