### ISSUE TITLE
php version issue

### ISSUE THREAD

**Issue by WebCrew** [InstantUpdate/CMS#7]
Hi mates :)

with all php versions newer as vs. php 5.4 the iu-application/controllers/process.php at line 165, 166 generates the following errors:

A PHP Error was encountered
Severity: 8192
Message: Non-static method BrowserOS::get_os() should not be called statically, assuming $this from incompatible context
Filename: controllers/process.php
Line Number: 166

A PHP Error was encountered
Severity: 8192
Message: Non-static method BrowserOS::get_browser_no_version() should not be called statically, assuming $this from incompatible context
Filename: controllers/process.php
Line Number: 167

Hope You can solv it ;)

Kind regards from Germany and huge thanks for the awesome IU-CMS.

Andy

**Comment by avramovic** [comment]
Hello!

Sorry for the late reply, it seems I did not get email about this issue. Anyway, it should be fixed now: https://github.com/InstantUpdate/CMS/commit/6e52f4b6c95226edd60c57c4861697f7ee1766d6

**Comment by WebCrew** [comment]
Yes its fixed :) thx a lot :)

You`ve done a great job ;)
