### ISSUE TITLE
Cant login after install

### ISSUE THREAD

**Issue by ob7** [InstantUpdate/CMS#9]
Tells me I have wrong username and password but I know its right.  Debug console shows lots of errors, one of which is broken link to jquery ui.  There is a get template directory php line before an external link in the auth_login php file.

**Comment by ob7** [comment]
The database is not even being populated on install, but the install says it goes through fine.  Is this even for real?  My server has the necessary requirements that's for sure. I'm installing on Apache.  I think you should check this out, as I'm seeing lots of errors and if this has been this way for over a year I don't see how anyone could be using this cms.

**Comment by ob7** [comment]
I would really like to get this working, but it seems something is wrong with the repo.  Is it still being maintained?

**Comment by ob7** [comment]
This looks related:
http://my.instant-update.com/t/error-user-with-that-e-mail-does-not-exists/172

**Comment by avramovic** [comment]
Your database connection information is incorrect. I will update setup controller later today to include exact error message.

Sorry for the inconvenience.

**Comment by avramovic** [comment]
Can you try now, should be fixed with this: https://github.com/InstantUpdate/CMS/commit/4a2f2cf7305ef398d5726bbe812323c97467b3da

**Comment by ob7** [comment]
Thank you for fixing that, now it indeed will give an error if database connection failed.  I was able to figure this out using the mysqltest script from the URL above, and that is that for some reason, it is not trying to access mysql using the credentials in the database config file.  Instead, the error I get now when trying to connect is:
ERROR: Access denied for user 'www-data'@'localhost' (using password: NO)

www-data is my Apache user, but in my config file, I have the MYSQL user as ui_cms, and same for database name.  But its not saying it cant connect using those credentials, instead its saying it can't connect using default server credentials.  How can I fix this?  Its as if its not reading my config file, even though if I leave it blank it says I need to update it before installing.

Thanks for all your help,
David

**Comment by avramovic** [comment]
I'm afraid that is related to your server configuration, and not to the Instant Update.

Check in your `php.ini` if `sql.safe_mode` is set to 1 make it `Off` or remove it. And then restart Аpache.

**Comment by ob7** [comment]
Your spot on!  I wonder why in the world I had that enabled to begin with.  I think I was testing something and forgot to turn it off.  Thanks man your a life saver.

**Comment by avramovic** [comment]
Great, I'm glad it's working for you now! :)
